FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Копируем requirements для тестов
COPY requirements.txt .
COPY requirements.dev.txt .

# Устанавливаем Python зависимости
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements.dev.txt

COPY src/ ./src/

RUN groupadd -r lampa && useradd -r -g lampa lampa
RUN chown -R lampa:lampa /app

USER lampa